const mockEvents = {
city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1590133567000,
      duration: 7200000,
      id: '270806244',
      name: 'Scrum Tale Online Schnuppertraining',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593072000000,
      local_date: '2020-06-25',
      local_time: '10:00',
      updated: 1590133567000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 16,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/270806244/',
      description: '<p>Genaue Details und Handouts folgen noch.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1591087441000,
      duration: 5400000,
      id: '271029863',
      name: 'TW presents: Agile: from Theory to Practice',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591804800000,
      local_date: '2020-06-10',
      local_time: '18:00',
      updated: 1591087441000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 21,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/271029863/',
      description: '<p>About the talk:</p> <p>In this talk, Svenja and Hubert will show how the theory of Agile practices can be applied to real projects. Embracing the learnings from their daily work and bringing real case studies, they will share with you how to best implement Agile practices in your project.<br/>We welcome people with no or little experience of working in an Agile environment, and those who have more experience, but always wonder how to cultivate agile practices even further.</p> <p>Our speakers:</p> <p>Svenja joined ThoughtWorks as a software developer about a year ago. Since then, she learned a lot about agile team work and came to love the short feedback cycles.<br/>Hubert is an Infrastructure developer with Thoughtworks since 2019. He is fascinated how large cloud providers have influenced software development at large by making infrastructure a commodity.</p> <p>-------------------------------------------<br/>How to Join the Event:</p> <p>You do not have to have a Zoom account to attend the event with Zoom. You will be prompted to download the software, once you have clicked on the link provided. You may also wish to create a Zoom account, but that is not required to participate in a Zoom meeting.</p> <p>Please see the System Requirements at the following URL to ensure that you are ready to go: ',
      how_to_find_us: 'https://thoughtworks.zoom.us/j/99270567186',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1527221719000,
      duration: 12600000,
      id: 'mttrspybcjbgc',
      name: 'PHP User Group Munich Meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593016200000,
      local_date: '2020-06-24',
      local_time: '18:30',
      updated: 1527221719000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 11149962,
        name: 'TNG Technology Consulting',
        lat: 48.18619918823242,
        lon: 11.65478229522705,
        repinned: true,
        address_1: 'Betastr. 13a',
        city: 'Unterföhring',
        country: 'de',
        localized_country_name: 'Germany',
        phone: '+498921589960'
      },
      is_online_event: false,
      group: {
        created: 1357914433000,
        name: 'PHP User Group Munich',
        id: 6604672,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'phpugmunich',
        who: 'PHP Developers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/phpugmunich/events/mttrspybcjbgc/',
      description: '<p>Join us for interesting talks, fun discussions, and be part of the Munich PHP community!</p> <p>The program for this meetup has not been finalized yet. If you would like to hear about a specific topic, recommend a speaker, or give a talk yourself, contact us (via comments or send us a message',
      how_to_find_us: 'With S-bahn S8 to Unterföhring (10 Minute walk). Or Bus 233 to Betastrasse. (2 Minute walk). Lots of street parking available',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1590511644000,
      duration: 7200000,
      id: '270884519',
      name: 'Elementor Online-Meetup DACH - Webdesign-Workflow mit Elementor...',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591722000000,
      local_date: '2020-06-09',
      local_time: '19:00',
      updated: 1590563288000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 23,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1549966106000,
        name: 'Elementor München',
        id: 31146435,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Muenchen-Elementor-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Muenchen-Elementor-Meetup/events/270884519/',
      description: '<p>...einschließlich responsiver Optimierung</p> <p>In diesem Meetup zeigen wir Euch die wichtigsten Schritte und Methoden, um ein bestehendes Webdesign aus den mehr oder weniger klar definierten Anforderungen von Kunden oder für eigene Zwecke mit Hilfe von WordPress, Elementor und weiteren Tools umzusetzen.</p> <p>Wir schauen uns dabei an, wann bestimmte Elemente und Stile über das Theme bzw. den Customizer umgesetzt werden, und wann es besser ist, diese vollständig mit Hilfe von Elementor umzusetzen.</p> <p>Wir zeigen auch, wie Elementor dafür genutzt werden, kann, bestimmte Abläufe in WordPress zu vereinfachen und damit Zeit zu sparen.</p> <p>Präsentiert wird das Meetup vom Service-Provider Sascha Liem, der sich als Agentur-Betreiber seit Anfang des Jahres um die Leitung und Organisation der Berliner Elementor-Meetup-Gruppe kümmert.</p> <p>Dieses Online-Meetup wird aufgezeichnet und im Internet veröffentlicht. Mit der Teilnahme erklärst Du Dich damit einverstanden.</p> <p>Nach der Präsentation gibt es die Möglichkeit in kleineren Gruppen Fragen zu stellen und Erfahrungen mit Elementor auszutauschen.</p> <p>Bitte melde Dich an, um den Link zu dem Meetup zu erhalten.</p> <p>Die Anzahl der Teilnehmer ist aus technischen Gründen begrenzt. Deswegen melde Dich rechtzeitig an und erscheine pünktlich.</p> ',
      how_to_find_us: 'https://us02web.zoom.us/j/83754351853',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1590921899000,
      duration: 3600000,
      id: '270990181',
      name: 'TW hosts: Look before you code:What to consider before going into digital health',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591282800000,
      local_date: '2020-06-04',
      local_time: '17:00',
      updated: 1590921899000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/270990181/',
      description: '<p>This event is presented by our friends from Meetup AI Berlin. Check out their Meetup page for more info: <a href=\'https://www.meetup.com/de-DE/meetupai-Berlin/?_locale=de-DE\' class=\'linkified\'>https://www.meetup.com/de-DE/meetupai-Berlin/?_locale=de-DE</a></p> <p>ThoughtWorks will be the technical host for the talk.<br/>--------------------------------------------------------</p> <p>Dear Friends, Colleagues, and fellow Technologist,</p> <p>We keep the ball running for the Meetup.ai Global Series, now back to one of our favorite topics Healthcare, specifically what to consider before throwing you hat into this field. Especially with the COVID emergency, we saw an explosive interest from Data Scientist to analyze and predict the pandemic, often with little regard for epidemiological or medical information.</p> <p>To better prepare those wanting to get involved in this field or want to know more about the specific challenges or the industry, we bring on stage Dr. Johannes Starlinger.</p> <p>A big shoutout to our partners at Thoughtworks for supporting us in our event series! Special thanks to Stephanie, Jenna, and their team.</p> <p>About the talk:</p> <p>Digital health is the call of the hour: health data is more available than ever, machine learning solutions in Healthcare achieve astounding results, and legislation is always providing more favorable circumstances. So what are you waiting for?</p> <p>This talk will first explore the wide spectrum of health data we know today - both inside and outside the classical healthcare system - and then discuss a number of important aspects to consider (and to help you get started) when considering taking on the digital health adventure.</p> <p>Bio:<br/>Johannes studied Medicine at the Medical University of Vienna and Computer Science at Humboldt-Universität Berlin. After exploring the use of software architectures for Big Data analysis in medical settings during his Ph.D., he leads and contributed to several interdisciplinary research projects centered around health data management and analytics at Humboldt-Universität and Charité Berlin. Today, Johannes works as an independent consultant in digital health, has a small software development company, and enjoys sharing knowledge about applied digital health topics as a guest lecturer at Charité and Humboldt-Universität.</p> <p>Schedule</p> <p>17:00- Start and introductions</p> <p>17:45- Q&amp;A</p> <p>18:00- Networking ( Beta Version, let\'s see how it goes)</p> <p>Host: Nicholas Borsotto, Founder of Archgriffin Consulting and Co-founder of Meetup.ai</p> <p>We will have the pleasure of hosting some more of the topics you suggested in the future. If you missed the Typeform before and want to recommend speakers and topics, you can find it here: bit.ly/meetupaiglobal.</p> <p>Hope to see you all there!</p> <p>Nicholas Borsotto and the whole Meetup.ai Berlin Team</p> <p>--------------<br/>How to Join the Event with Zoom:</p> <p>You do not have to have a Zoom account to attend the event with Zoom. You will be prompted to download the software once you have clicked on the link that will be provided approximately 1 hour before the event begins.</p> <p>Check System Requirements at the following URL to ensure that you are ready to go: ',
      how_to_find_us: 'https://thoughtworks.zoom.us/j/99110137086',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1522694856000,
      duration: 10800000,
      id: 'lkgknpybcjbjc',
      name: 'Deutsch-Japanischer\u00ad Stammtisch',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593190800000,
      local_date: '2020-06-26',
      local_time: '19:00',
      updated: 1522694856000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      is_online_event: false,
      group: {
        created: 1512221367000,
        name: 'Deutsch-Japanischer Stammtisch',
        id: 26763059,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'deutsch-japanischer-stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/deutsch-japanischer-stammtisch/events/lkgknpybcjbjc/',
      description: '<p>Wir treffen uns einmal im Monat zum Sprach- und Kulturaustausch. Außerdem wird ein interessanter Vortrag rund um das Thema Japan gehalten. Das genaue Thema des Vortrags wird dann noch vorher bekanntgegeben.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1564222784000,
      duration: 10800000,
      id: 'sqlrfrybckbhb',
      name: 'Repair Café Schwabing',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593950400000,
      local_date: '2020-07-05',
      local_time: '14:00',
      updated: 1564222784000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 26538112,
        name: 'Seidlvilla',
        lat: 48.15855026245117,
        lon: 11.587692260742188,
        repinned: false,
        address_1: 'Nikolaiplatz 1b',
        city: 'München ',
        country: 'DE',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1490371801000,
        name: 'Repair Café Meetup',
        id: 22994509,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Repair-Cafe-Meetup',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Repair-Cafe-Meetup/events/sqlrfrybckbhb/',
      description: '<p>Jeden ersten Sonntag ab 14 Uhr bis 17 Uhr finde in der Seidlvilla in Schwabing unser Repair Café statt. Bringt Eure kaputten Uhren, Elektro Kleinteile, Haushaltsgeräte, Kleidungsstücke, Taschen, Textilien sowie Laptops oder Handys die repariert werden müssen. Wenn ihr selbst wisst, wie es geht, und mitmachen wollt, freuen wir uns auf deine Mithilfe bei reparieren hierzu bitte vorab melden unter [masked]. </p> <p>Every first Sunday from 2pm to 5pm the Repair Café Schwabing takes place in the Seidlvilla in Schwabing (U3 and 6 Münchner Freiheit). Bring your broken watches, electronic items, household items, clothes, bags and other textiles as well as laptops and phones. If you know how to repair and want to join in, we are looking forward to your contribution. Please let us know in advance, if you will be part of the repair team: [masked] and we will give you further information.</p> ',
      how_to_find_us: 'zwischen Münchner Freiheit und Giselastraße',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1588712120000,
      duration: 5400000,
      id: '270469367',
      name: 'Scrum Speakers @ Online',
      rsvp_limit: 45,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1594137600000,
      local_date: '2020-07-07',
      local_time: '18:00',
      updated: 1590513895000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 18,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1558423773000,
        name: 'Scrum Speakers',
        id: 31977973,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ScrumSpeakers',
        who: 'Scrum Speakers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ScrumSpeakers/events/270469367/',
      description: '<p>Agenda:</p> <p>18:00 Gather and settle down</p> <p>18:05 Opening</p> <p>- Agile Game<br/>MacGyver | A funny game to nurture the agile mindset within scrum teams | English | Mihai Donos | Agile Coach</p> <p>- Speeches<br/>-- You can sign up below to make a speech<br/><a href=',
      how_to_find_us: 'meet.google.com/yrb-yjnm-kcv',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1590851812000,
      duration: 7200000,
      id: '270975791',
      name: 'PythonShow #6: Growing Plants, running PyBusiness',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591288200000,
      local_date: '2020-06-04',
      local_time: '18:30',
      updated: 1590851878000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 45,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1435577493000,
        name: 'PyMunich',
        id: 18706411,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'PyMunich',
        who: 'Pythonistas',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/PyMunich/events/270975791/',
      description: '<p>The Python Show #6 🎥 Agenda:</p> <p>- Maria Jose Molina-Contreras (Berlin): \'How to build an indoor garden with microcontrollers, Circuitpython and IoT\'</p> <p>- Lasse Schuirmann (Hamburg): ',
      how_to_find_us: 'https://youtu.be/yW6EphF16UQ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1579163951000,
      duration: 10800000,
      id: 'ddhzmrybcjbwb',
      name: 'Drupal User Group Munich @EineWeltHaus',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592413200000,
      local_date: '2020-06-17',
      local_time: '19:00',
      updated: 1579163951000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26078691,
        name: 'EineWeltHaus',
        lat: 48.137691497802734,
        lon: 11.55286979675293,
        repinned: true,
        address_1: 'Schwanthalerstraße 80',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1410086988000,
        name: 'München Drupal User Group Meetup',
        id: 16845232,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Drupal-User-Group-Meetup',
        who: 'Drupalistas',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Drupal-User-Group-Meetup/events/ddhzmrybcjbwb/',
      description: '<p>Das Meetup ist sowohl für Drupal-AnwenderInnen, -EntwicklerInnnen, -EinsteigerInnen als auch Professionals geeignet. Wir reden nicht nur über Drupal, sondern auch über Community, React, Vue.js, Docker, Symfony, PHP, UX und viele andere Dinge. Andere Communities sind bei uns herzlich Willkommen!</p> <p>The meetup is for any level of Drupal user. We are not talking Drupal only but also about community, React, Vue.js, Docker Symfony, PHP, UX and much more stuff. Other communities are very welcome.</p> <p>---<br/>Vortrag 1 / Talk 1 - tbd<br/>---<br/>Vortrag 2 /Talk 2 - tbd<br/>---</p> <p>Wir suchen immer nach interessanten Themen! Wenn du interessiert daran bist, einen Vortrag oder ein interessantes Projekt vorzustellen (deutsch oder englisch entscheidest du!), melde dich bei uns.</p> <p>Im Anschluss der Talks gibt es genügend Zeit für Diskussion und Networking. Wir sehen uns dort!</p> <p>---</p> <p>If you are interested in giving a talk or to speak about a interesting project, drop us a line. We are always looking for talks.</p> <p>Followed by discussion and networking.<br/>See you there!</p> ',
      how_to_find_us: 'Raum 109. Bitte den Raumbelegungsplan am Eingang beachten.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1578988881000,
      duration: 10800000,
      id: '267900600',
      name: 'München OutSystems Meetup - Save the date',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1597248000000,
      local_date: '2020-08-12',
      local_time: '18:00',
      updated: 1578988881000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      is_online_event: false,
      group: {
        created: 1560928375000,
        name: 'Offizielle OutSystems München Meetup Gruppe',
        id: 32208133,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-OutSystems-Community',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-OutSystems-Community/events/267900600/',
      description: '<p>Das Thema wird in Kürze veröffentlicht.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1582305887000,
      duration: 7200000,
      id: '268885897',
      name: 'Münchner Digitalagenturen Stammtisch',
      rsvp_limit: 20,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592407800000,
      local_date: '2020-06-17',
      local_time: '17:30',
      updated: 1589319872000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      venue: {
        id: 26345484,
        name: 'Leib und Seele',
        lat: 48.145721435546875,
        lon: 11.593596458435059,
        repinned: true,
        address_1: 'Oettingenstraße 36',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      is_online_event: false,
      group: {
        created: 1579267827000,
        name: 'Münchner Digitalagenturen Stammtisch',
        id: 33213723,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Muenchner-Digitalagenturen-Stammtisch',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Muenchner-Digitalagenturen-Stammtisch/events/268885897/',
      description: '<p>- Welche Neuigkeiten gibt es in der Branche?<br/>- Wie entwickelt sich der Markt?<br/>- Mit welchen Herausforderungen hast Du zu kämpfen?<br/>- Wer tummelt sich eigentlich noch so in der Branche?<br/>- Welche Erfahrungen habt ihr mit den verschiedenen Aufbau und Ablauforganisation gemacht?<br/>- Welche Tools setzt ihr ein?<br/>- Natürlich sind auch alle \'businessfremden\' Themen, die uns so beschäftigten, mehr als erwünscht. Über Business reden wir schließlich den ganzen Tag.</p> <p>In wechselnden Locations soll der lockere Austausch Menschen aus der Führungsebene Münchner Digitalagenturen zusammenbringen.<br/>Dieses Mal treffen wir uns im Restaurant in der Oettingenstr. 36 - ein Tisch reserviert.</p> <p>Alles kann, nichts muss!</p> <p>Wir freuen uns auf erfrischende Gespräche mit (ent)spannenden Menschen.</p> <p>Euer<br/>Benedikt Hermann<br/>Trion Digitalagentur</p> ',
      how_to_find_us: 'Im Restaurant ist ein Tisch auf reserviert',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1591047567000,
      duration: 7200000,
      id: '271022487',
      name: ' Sharing & review of your photos (Online)',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591432200000,
      local_date: '2020-06-06',
      local_time: '10:30',
      updated: 1591047567000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      is_online_event: false,
      group: {
        created: 1500930561000,
        name: 'Photography Workshops Munich',
        id: 25119735,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munchen-Photography-Workshops',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munchen-Photography-Workshops/events/271022487/',
      description: '<p>This is an online meeting using the software Zoom.</p> <p>The link to the Zoom meeting will be visible to those who joined via com/en/event/50/sharing-review-of-your-photos-online-20200606</a></p> <p>You probably have had plenty of time to go over your old photos while staying at home, or you may have new photos of the empty streets that you want to share! Bring them along, and let\'s discuss in a small friendly group how they could be improved!</p> <p>It\'s a great way to get a new perspective on photos you like - and probably on those that you think didn\'t quite work out the way you planned them to be. Probably we can find a fix :)</p> <p>Do limit your choice of photos to less than five, so we can concentrate on the story you want to tell.</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1581065421000,
      duration: 143940000,
      id: '268530677',
      name: 'OUTDOOR COWORKING 2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593151200000,
      local_date: '2020-06-26',
      local_time: '08:00',
      updated: 1581065462000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      is_online_event: false,
      group: {
        created: 1442238396000,
        name: 'OUTDOOR COWORKING',
        id: 18930367,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'outdoor-coworking-day',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/outdoor-coworking-day/events/268530677/',
      description: '<p>Coworking mal ganz woanders, aber doch im eigenen Van. Mit ganz wem anders, aber doch unter Freunden. Lüftet mit bekannten Unternehmen, Vanlifeworkern und spannenden Personen den Büroalltag mal ordentlich durch. 2019 waren von Firmen wie SIXT, ReCup, andere aus der Sport- oder Automotive-Branche, bis hin zu Agenturen, Freelancern, Fotografen und Influencern alles dabei.<br/>Wir laden Euch ein, Teil unseres #woooday in der Natur zu sein.</p> <p>Buchung unter: www.outdoor-coworking-day.de</p> ',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1527221719000,
      duration: 12600000,
      id: 'mttrspybckbdc',
      name: 'PHP User Group Munich Meeting',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1595435400000,
      local_date: '2020-07-22',
      local_time: '18:30',
      updated: 1527221719000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 5,
      venue: {
        id: 11149962,
        name: 'TNG Technology Consulting',
        lat: 48.18619918823242,
        lon: 11.65478229522705,
        repinned: true,
        address_1: 'Betastr. 13a',
        city: 'Unterföhring',
        country: 'de',
        localized_country_name: 'Germany',
        phone: '+498921589960'
      },
      is_online_event: false,
      group: {
        created: 1357914433000,
        name: 'PHP User Group Munich',
        id: 6604672,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'phpugmunich',
        who: 'PHP Developers',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/phpugmunich/events/mttrspybckbdc/',
      description: '<p>Join us for interesting talks, fun discussions, and be part of ',
      how_to_find_us: 'With S-bahn S8 to Unterföhring (10 Minute walk). Or Bus 233 to Betastrasse. (2 Minute walk). Lots of street parking available.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1584390889000,
      duration: 14400000,
      id: '269466550',
      name: '3. agiles PM-Trendforum 2020 (digital) am 25.06.2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593100800000,
      local_date: '2020-06-25',
      local_time: '18:00',
      updated: 1587540743000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 52,
      is_online_event: false,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/269466550/',
      description: '<p>MS-Teams Meeting (Link):</p',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1590520105000,
      duration: 3600000,
      id: '270887647',
      name: 'Freelancing in Europe 2020',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591185600000,
      local_date: '2020-06-03',
      local_time: '14:00',
      updated: 1590520381000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 9,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1552473723000,
        name: 'Freelancing in München',
        id: 31379005,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Freelancing-in-Munchen',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Freelancing-in-Munchen/events/270887647/',
      description: '<p>Liebe Freelancer,<',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1590561135000,
      duration: 27000000,
      id: '270899417',
      name: 'XConf Online',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1593160200000,
      local_date: '2020-06-26',
      local_time: '10:30',
      updated: 1590572379000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 30,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/270899417/',
      description: '<p>Please register for Z',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1589268553000,
      duration: 3600000,
      id: '270599805',
      name: 'Projekte unternehmensweit planen, steuern und kommunizieren in MS Office 365',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1592989200000,
      local_date: '2020-06-24',
      local_time: '11:00',
      updated: 1589268676000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 13,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/270599805/',
      description: '<p>Link zur Landing Page mit den Logininformationen zu MS-Teams:',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1590659581000,
      duration: 7200000,
      id: '270925336',
      name: 'Webpack Encore - Asset Management für den Rest von uns | TYPO3 Meetup München',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1591117200000,
      local_date: '2020-06-02',
      local_time: '19:00',
      updated: 1590659581000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 17,
      venue: {
        id: 26906060,
        name: 'Online event',
        repinned: false,
        country: '',
        localized_country_name: ''
      },
      is_online_event: true,
      group: {
        created: 1474525425000,
        name: 'Munich TYPO3 User Group (MTUG)',
        id: 20453681,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-TYPO3-User-Group',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-TYPO3-User-Group/events/270925336/',
      description: '<p>Wer moderne Frontend-Technologie in seinen Projekten einsetzt, kommt an Webpack nicht vorbei. Obwohl die halbe Welt diesen mächtigen Bundler zum Bauen von Assets einsetzt, kann dessen Konfiguration akademische Kenntnisse der Interna erfordern; Symfony bietet mit Encore einen schmalen Wrapper um Webpack an, mit dem Asset Building auch für mehrere Environ',
      visibility: 'public',
      member_pay_fee: false
    }
  ]
}

export { mockEvents };